# Ubuntu 18.04 with JDK 11
# Build image with:  docker build -t raft-node:latest .

FROM ubuntu:18.04

# Install all dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y net-tools iputils-ping maven gradle nmap wget git vim build-essential && \
    apt-get clean

# Create a new directory as the working directory
RUN mkdir /csci251

# Copy over the files we need
COPY pom.xml /csci251/
COPY README.md /csci251/
COPY docker_scripts /csci251/docker_scripts
COPY src /csci251/src

# setup working directory in the container
WORKDIR /csci251

# go into the working directory and build java package using maven
RUN cd /csci251 && mvn package
